package com.nmh.commerce.coupon.mock;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class FakeCouponStockRepository implements CouponStockRepository {
    private final List<CouponStock> data = new ArrayList<>();
    private Long autoGeneratedId = 0L;

    @Override
    public CouponStock save(CouponStock couponStock) {
        if (couponStock.id == null || couponStock.id == 0) {
            CouponStock newCouponStock = CouponStock.builder()
                .id(++autoGeneratedId)
                .couponId(couponStock.couponId)
                .remainingQuantity(couponStock.remainingQuantity)
                .build();
            data.add(newCouponStock);
            return newCouponStock;
        } else {
            data.removeIf(it -> it.id.equals(couponStock.id));
            data.add(couponStock);
            return couponStock;
        }
    }

    @Override
    public Optional<CouponStock> findByCouponId(Long couponId) {
        return data.stream()
            .filter(it -> it.couponId.equals(couponId))
            .findAny();
    }

    @Override
    public CouponStock update(CouponStock couponStock) {
        data.removeIf(it -> it.id.equals(couponStock.id));
        data.add(couponStock);
        return couponStock;
    }
}
