package com.nmh.commerce.coupon.mock;

import com.nmh.commerce.coupon.CouponStock;
import com.nmh.commerce.coupon.CouponStockRepository;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class FakeCouponStockRepository implements CouponStockRepository {
    private final List<CouponStock> data = new ArrayList<>();
    private Long autoGeneratedId = 0L;

    @Override
    public CouponStock save(CouponStock couponStock) {
        if (couponStock.getId() == null || couponStock.getId() == 0) {
            CouponStock newCouponStock = CouponStock.builder()
                .id(++autoGeneratedId)
                .couponId(couponStock.getCouponId())
                .remainingQuantity(couponStock.getRemainingQuantity())
                .build();
            data.add(newCouponStock);
            return newCouponStock;
        } else {
            data.removeIf(it -> it.getId().equals(couponStock.getId()));
            data.add(couponStock);
            return couponStock;
        }
    }

    @Override
    public Optional<CouponStock> findByCouponId(Long couponId) {
        return data.stream()
            .filter(it -> it.getCouponId().equals(couponId))
            .findAny();
    }

    @Override
    public CouponStock update(CouponStock couponStock) {
        data.removeIf(it -> it.getId().equals(couponStock.getId()));
        data.add(couponStock);
        return couponStock;
    }
}
